version: 2
updates:
- package-ecosystem: nuget
  directory: "/Plotly.Blazor"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  reviewers:
  - sean-mcleish
  ignore:
  - dependency-name: Microsoft.AspNetCore.Components
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
    - 5.0.5
  - dependency-name: GitVersion.MsBuild
    versions:
    - 5.6.7
  - dependency-name: Microsoft.AspNetCore.Components.Web
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: System.Text.Json
    versions:
    - 5.0.1
